### ISSUE TITLE
Error Play service 

### ISSUE THREAD

**Issue by nyok92** [immstudios/nebula-hub#2]
Hi ! i'v got another error when cueing a clip in rundown :

2021-03-03 12:57:04 DEBUG       meta            Saving asset ID:25 (VIDEO)
2021-03-03 12:57:10 GOOD NEWS   meta            asset ID:25 (VIDEO): Turning online
2021-03-03 12:57:10 DEBUG       meta            Saving asset ID:25 (VIDEO)
2021-03-03 12:57:23 ERROR       play            Unable to cue {get_object_state_name(playout_status)} playout file
2021-03-03 12:57:24 INFO        psm             Sending asset ID:25 (VIDEO) to playout casparcg : Job created

 &
 ERROR       hub             API Request 'playout' by audio failed with code  404 Unable to cue {get_object_state_name(playout_status)} playout file
2021-03-03 13:01:08 INFO        hub             audio requested api method jobs
2021-03-03 13:01:08 ERROR       hub             Exception

    Traceback (most recent call last):
      File "/opt/nebula/vendor/cherryadmin/cherryadmin/handler.py", line 301, in api
        response = api_method(**request)
      File "/opt/nebula/nx/api/jobs.py", line 140, in api_jobs
        row["action_title"] = config["actions"][id_action]["title"]
    KeyError: 2

Did i missed something ? 
Thks !

**Comment by martastain** [comment]
This seems to be a configuration problem (again - my problem, since the documentation still sucks).

I guess you see the item in the rundown as "REMOTE"? CasparCG currently needs to have media files copied locally (which is about to be changed, but at the moment it is required), so the psm service (playout storage monitor) tries to copy your media file to the playout storage (as soon you put it to the playlist and it is about to be broadcasted). It creates a job using action id 2 (which is defined in the channel configuration using the `send_action` key). 

Since you probably don't have the action configured, you are getting that error in the job monitor. And since there is no local copy on a playout storage, you are getting the 404 error.

Try to add the following to the configuration template:

```
data["actions"][2] = ["playout", "conv", "template/actions/playout.xml"]
```
(our convention, which you are not obliged to follow is to use action id 1 for encoding low-res previews and id 2 for transfer to the playout server)

and create `template/actions/playout.xml` file with the following content

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings>
    <allow_if>True</allow_if>
    <task mode="ffmpeg">
        <param name="c:a">copy</param>
        <param name="c:v">"copy"</param>
        <output storage="asset.get_playout_storage(1)" direct="1"><![CDATA[asset.get_playout_path(1)]]></output>
    </task>
</settings>
```

VLC and Conti can play REMOTE media files and I'm working on an update which will allow CasparCG to play them as well - this will be however limited to Linux version of Caspar, since it will use symlinks.

Hope this helps.... and I seriously need to find a ghostwriter for docs :)

**Comment by nyok92** [comment]
Hi , thanks it worked; now the status changed to online: The file is copied from ID1:production to ID2:playout.
But when playing it i've got this error:

ERROR       hub             API Request 'playout' by audio failed with code  404 Unable to cue "nebula-1" 404 LOADBG FAILED - args: {'timeout': '1', 'action': 'cue', 'id_channel': '1', 'session_id': 'bc34a7f3fd4bc4d5479018aeec2f821ccb883013d7e3f160d10f65f005774a63', 'initiator': '448950ee-7cd9-11eb-a5c3-a0510ba6e5e0', 'full_path': '/mnt/nebula_02/media.dir/nebula-1.mov', 'mark_in': 0, 'mark_out': 0, 'auto': True, 'loop': False}

By the way, i can't preview my assets in the detail assets/preview on firefly.

**Comment by nyok92** [comment]
My bad for the error 404 with LOADBG on Casparcg, i had a misconfiguration of the media folder ... :)
But for the preview on hub or firefly, do i have to create an action like the one for playout copy ?

**Comment by martastain** [comment]
Exactly - create another action the same way you did for playout. We use something like the following. It should work out of the box and create low-res media files for all of your media files.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<settings>
    <allow_if>True</allow_if>
    <create_if><![CDATA[asset["content_type"] == VIDEO and asset["status"] == ONLINE]]></create_if>
    <start_if><![CDATA[asset["status"] == ONLINE and "video/codec" in asset.meta]]></start_if>
    <skip_if><![CDATA[asset.has_proxy]]></skip_if>

    <task mode="ffmpeg">
        <param name="s">"640x360"</param>
        <param name="r">25</param>
        <param name="pix_fmt">"yuv420p"</param>
        <param name="c:v">"libx264"</param>
        <param name="profile:v">"main"</param>
        <param name="preset:v">"fast"</param>
        <param name="g">1</param>
        <param name="c:a">"libfdk_aac"</param>
        <param name="b:a">"128k"</param>
        <param name="ar">48000</param>
        <param name="video_track_timescale">"25"</param>
        <param name='movflags'>"faststart"</param>
        <output storage="asset.proxy_storage">asset.proxy_path</output>
    </task>
</settings>
```

**Comment by nyok92** [comment]
Thanks, it's working great !
